version: '3.8'
services:
  backend:
    build:
      context: ./pokemon_gashapon_backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=180541
      - DB_NAME=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./pokemon_gashapon_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=180541
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: